//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public string conpania { get; set; }
        public string contacto { get; set; }
        public string celular { get; set; }
        public string pass { get; set; }
    }
}
